Repository microsoft/MixedReality-WebRTC, pull requests merged in 2020-04, with the labels that each got.

#251 More fixes for M.MR.WebRTC.Native.dll rename
  docs/manual/building.md
  docs/manual/download.md
  docs/manual/helloworld-unity-importwebrtc.md
  docs/manual/installation.md
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/WSA/ARM/mrwebrtc.dll.meta
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/WSA/ARM/mrwebrtc.pdb.meta
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/WSA/x86/mrwebrtc.dll.meta
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/WSA/x86/mrwebrtc.pdb.meta
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/WSA/x86_64/mrwebrtc.dll.meta
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/WSA/x86_64/mrwebrtc.pdb.meta
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/Win32/x86/mrwebrtc.dll.meta
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/Win32/x86/mrwebrtc.pdb.meta
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/Win32/x86_64/mrwebrtc.dll.meta
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Plugins/Win32/x86_64/mrwebrtc.pdb.meta
Labels: bug

#256 Add IAudioTrack and IVideoTrack interfaces
  libs/Microsoft.MixedReality.WebRTC/IAudioTrack.cs
  libs/Microsoft.MixedReality.WebRTC/IVideoTrack.cs
  libs/Microsoft.MixedReality.WebRTC/LocalAudioTrack.cs
  libs/Microsoft.MixedReality.WebRTC/LocalVideoTrack.cs
  libs/Microsoft.MixedReality.WebRTC/RemoteAudioTrack.cs
  libs/Microsoft.MixedReality.WebRTC/RemoteVideoTrack.cs
Labels: enhancement

#259 Fix license of TestReceiveAV/Program.cs
  examples/TestReceiveAV/Program.cs
Labels: bug

#269 Add support for multi-track to TestAppUWP
  examples/TestAppUwp/AddAudioTrackPage.xaml
  examples/TestAppUwp/AddAudioTrackPage.xaml.cs
  examples/TestAppUwp/AddVideoTrackPage.xaml
  examples/TestAppUwp/AddVideoTrackPage.xaml.cs
  examples/TestAppUwp/App.xaml
  examples/TestAppUwp/App.xaml.cs
  examples/TestAppUwp/DebugConsolePage.xaml
  examples/TestAppUwp/DebugConsolePage.xaml.cs
  examples/TestAppUwp/MainPage.xaml
  examples/TestAppUwp/MainPage.xaml.cs
  examples/TestAppUwp/MediaPlayerPage.xaml
  examples/TestAppUwp/MediaPlayerPage.xaml.cs
  examples/TestAppUwp/Microsoft.MixedReality.WebRTC.TestAppUWP.csproj
  examples/TestAppUwp/Model/SessionModel.cs
  examples/TestAppUwp/NodeDssSignaler.cs
  examples/TestAppUwp/SessionPage.xaml
  examples/TestAppUwp/SessionPage.xaml.cs
  examples/TestAppUwp/SettingsPage.xaml
  examples/TestAppUwp/SettingsPage.xaml.cs
  examples/TestAppUwp/SignalingPage.xaml
  examples/TestAppUwp/SignalingPage.xaml.cs
  examples/TestAppUwp/TrackListPage.xaml
  examples/TestAppUwp/TrackListPage.xaml.cs
  examples/TestAppUwp/TracksPage.xaml
  examples/TestAppUwp/TracksPage.xaml.cs
  examples/TestAppUwp/ViewModel/AudioCaptureViewModel.cs
  examples/TestAppUwp/ViewModel/CollectionViewModel.cs
  examples/TestAppUwp/ViewModel/Converters.cs
  examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
  examples/TestAppUwp/ViewModel/NotifierBase.cs
  examples/TestAppUwp/ViewModel/SessionViewModel.cs
  examples/TestAppUwp/ViewModel/SignalerViewModel.cs
  examples/TestAppUwp/ViewModel/TransceiverCollectionViewModel.cs
  examples/TestAppUwp/ViewModel/TransceiverViewModel.cs
  examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
Labels: bug, multitrack

#291 Remote PeerConnection interface from internal impl
  libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/utils.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/utils.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj
  libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj.filters
  libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj
  libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj.filters
Labels: clean-up

#99 Remote audio feature
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Examples/VideoChatDemo/VideoChatDemo.prefab
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/AudioReceiver.cs
  libs/Microsoft.MixedReality.WebRTC/AudioTrackReadBuffer.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/AudioTrackReadBufferInterop.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
  libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/include/peer_connection_interop.h
  libs/mrwebrtc/src/interop/global_factory.cpp
  libs/mrwebrtc/src/interop/global_factory.h
  libs/mrwebrtc/src/interop/peer_connection_interop.cpp
  libs/mrwebrtc/src/media/audio_track_read_buffer.cpp
  libs/mrwebrtc/src/media/audio_track_read_buffer.h
  libs/mrwebrtc/src/pch.h
  libs/mrwebrtc/src/peer_connection.cpp
  libs/mrwebrtc/src/peer_connection.h
  libs/mrwebrtc/src/utils.h
  libs/mrwebrtc/test/pch.h
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj
Labels: enhancement

#299 Update README.md with the most recent changes
  README.md
  docs/manual/architecture.png
Labels: doc

#310 Fix C# transceiver test
  tests/Microsoft.MixedReality.WebRTC.Tests/TransceiverTests.cs
Labels: bug

#308 Earlier and more consistent DataChannelAdded event
  libs/mrwebrtc/src/data_channel.cpp
  libs/mrwebrtc/src/peer_connection.cpp
Labels: bug

#302 Add warning for missing per-track preferred codec
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/AudioSender.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/VideoSender.cs
Labels: bug
