Repository microsoft/MixedReality-WebRTC, pull requests merged in 2020-02, with the labels that each got.

#194 NodeDssSignaler: CO_GetAndProcessFromServer(): set timeSincePollMs = …
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs
Labels: enhancement

#195 Async SetRemoteDescription to avoid race condition
  examples/TestAppUwp/MainPage.xaml.cs
  libs/Microsoft.MixedReality.WebRTC.Native/include/interop_api.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.h
  libs/Microsoft.MixedReality.WebRTC.Native/test/data_channel_tests.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/test/peer_connection_test_helpers.h
  libs/Microsoft.MixedReality.WebRTC.Native/test/peer_connection_tests.cpp
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Editor/EditorTests.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
  libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/DataChannelTests.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/LocalVideoTrackTests.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/PeerConnectionTests.cs
Labels: breaking change, enhancement

#196 2-step external video track creation for callbacks
  libs/Microsoft.MixedReality.WebRTC.Native/include/external_video_track_source_interop.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/interop/external_video_track_source_interop.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source_impl.h
  libs/Microsoft.MixedReality.WebRTC.Native/test/external_video_track_source_tests.cpp
  libs/Microsoft.MixedReality.WebRTC/Interop/ExternalVideoTrackSourceInterop.cs
Labels: breaking change, enhancement

#199 Add RefPtr<GlobalFactory> to TrackedObject
  libs/Microsoft.MixedReality.WebRTC.Native/src/interop/external_video_track_source_interop.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/interop/global_factory.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/interop/global_factory.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source_impl.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/media/local_video_track.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/media/local_video_track.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/tracked_object.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/tracked_object.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj
  libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj.filters
  libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj
  libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj.filters
Labels: enhancement

#200 Set `negotiated` flag correctly
  libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
Labels: bug

#201 Expose some library-wide functionalities
  libs/Microsoft.MixedReality.WebRTC.Native/include/interop_api.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/interop/global_factory.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/interop/global_factory.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/test/Microsoft.MixedReality.WebRTC.Native.Tests.vcxproj
  libs/Microsoft.MixedReality.WebRTC.Native/test/library_tests.cpp
  libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
  libs/Microsoft.MixedReality.WebRTC/Library.cs
Labels: enhancement
