Repository microsoft/MixedReality-WebRTC, pull requests merged in 2020-03, with the labels that each got.

#208 Link against core PDBs when building interop DLL
  libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj
  libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj.filters
  libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj
  libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj.filters
  tools/ci/computePdbPackageVars.ps1
  tools/ci/copyPdbsForBuilding.ps1
  tools/ci/copyPdbsForPackaging.ps1
  tools/ci/generateCppPackagesConfig.ps1
  tools/ci/modifyCppProject.ps1
  tools/ci/release-core-nosign.yaml
  tools/ci/templates/jobs-cpp.yaml
  tools/ci/templates/jobs-libwebrtc-uwp.yaml
  tools/ci/templates/jobs-libwebrtc-win32.yaml
Labels: enhancement

#219 Fix transceiver streams for Plan B
  libs/Microsoft.MixedReality.WebRTC.Native/include/peer_connection_interop.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/media/transceiver.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/src/media/transceiver.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/test/transceiver_tests.cpp
Labels: bug

#229 Restore extra params override in remote description
  libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
Labels: bug

#241 Fix marshaling of data channel create config
  libs/Microsoft.MixedReality.WebRTC.Native/include/interop_api.h
  libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
  libs/Microsoft.MixedReality.WebRTC.Native/test/data_channel_tests.cpp
  libs/Microsoft.MixedReality.WebRTC/Interop/DataChannelInterop.cs
Labels: bug

#236 Update Unity tutorial for multi-track changes
  docs/index.md
  docs/manual/cs/cs-peerconnection.md
  docs/manual/cs/cs-signaling.md
  docs/manual/cs/helloworld-cs-connection-core3.md
  docs/manual/cs/helloworld-cs-connection-uwp.md
  docs/manual/cs/helloworld-cs-mediatracks-core3.md
  docs/manual/cs/helloworld-cs-mediatracks-uwp.md
  docs/manual/cs/helloworld-cs-setup-core3.md
  docs/manual/cs/helloworld-cs-setup-uwp.md
  docs/manual/helloworld-unity-1.png
  docs/manual/helloworld-unity-10.png
  docs/manual/helloworld-unity-11.png
  docs/manual/helloworld-unity-12.png
  docs/manual/helloworld-unity-13.png
  docs/manual/helloworld-unity-13b.png
  docs/manual/helloworld-unity-14.png
  docs/manual/helloworld-unity-15.png
  docs/manual/helloworld-unity-2.png
  docs/manual/helloworld-unity-3.png
  docs/manual/helloworld-unity-4.png
  docs/manual/helloworld-unity-5.png
  docs/manual/helloworld-unity-6.png
  docs/manual/helloworld-unity-7.png
  docs/manual/helloworld-unity-8.png
  docs/manual/helloworld-unity-8b.png
  docs/manual/helloworld-unity-8c.png
  docs/manual/helloworld-unity-9.png
  docs/manual/helloworld-unity-connection.md
  docs/manual/helloworld-unity-createproject.md
  docs/manual/helloworld-unity-importwebrtc.md
  docs/manual/helloworld-unity-localvideo.md
  docs/manual/helloworld-unity-peerconnection.md
  docs/manual/helloworld-unity-remotevideo.md
  docs/manual/helloworld-unity-signaler.md
  docs/manual/unity-integration.md
  docs/manual/unity-localaudiosource.md
  docs/manual/unity-localvideosource.md
  docs/manual/unity-mediaplayer.md
  docs/manual/unity-remoteaudiosource.md
  docs/manual/unity-remotevideosource.md
  docs/manual/unity-signaler.md
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Examples/NodeDssSignalerUI.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Examples/StandaloneDemo/LocalOnlySignaler.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs
Labels: doc

#243 Add migration guide
  docs/index.md
  docs/manual/migration-guide.md
  docs/manual/toc.md
Labels: doc

#245 Add warnings to docs where due
  docs/manual/cs/helloworld-cs-core3.md
  docs/manual/cs/helloworld-cs-uwp.md
  docs/manual/download.md
  docs/manual/installation.md
Labels: bug, doc
