Repository microsoft/MixedReality-WebRTC, pull requests merged in 2020-05, with the labels that each got.

#316 Delete unused components before CG scan
  tools/build/libwebrtc/mrwebrtc.ps1
  tools/ci/mapVariables.ps1
Labels: bug

#317 Show video capture encoding in format in list
  examples/TestAppUwp/AddVideoTrackPage.xaml
  examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
  examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
Labels: bug

#320 Prevent deadlock on SetRemoteDescriptionAsync fail
  libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
  libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/src/interop/interop_api.cpp
  libs/mrwebrtc/src/interop/peer_connection_interop.cpp
  libs/mrwebrtc/src/peer_connection.cpp
  libs/mrwebrtc/src/peer_connection.h
  libs/mrwebrtc/test/test_utils.cpp
  libs/mrwebrtc/test/test_utils.h
  tests/Microsoft.MixedReality.WebRTC.Tests/PeerConnectionTestBase.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/PeerConnectionTests.cs
Labels: breaking change, bug

#322 Use enum and message type for SDP messages
  examples/TestAppUwp/Model/SessionModel.cs
  examples/TestAppUwp/NodeDssSignaler.cs
  examples/TestNetCoreConsole/NamedPipeSignaler.cs
  examples/TestNetCoreConsole/Program.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Examples/StandaloneDemo/LocalOnlySignaler.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Editor/EditorTests.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/Signaler.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
  libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
  libs/Microsoft.MixedReality.WebRTC/Tracing/MainEventSource.cs
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/src/interop/interop_api.cpp
  libs/mrwebrtc/src/peer_connection.cpp
  libs/mrwebrtc/src/peer_connection.h
  libs/mrwebrtc/src/sdp_utils.cpp
  libs/mrwebrtc/src/sdp_utils.h
  libs/mrwebrtc/test/data_channel_tests.cpp
  libs/mrwebrtc/test/peer_connection_test_helpers.h
  libs/mrwebrtc/test/peer_connection_tests.cpp
  tests/Microsoft.MixedReality.WebRTC.Tests/PeerConnectionTestBase.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/PeerConnectionTests.cs
Labels: breaking change, enhancement

#286 [TestAppUWP] Save/restore preferred codecs via app settings
  examples/TestAppUwp/MainPage.xaml.cs
  examples/TestAppUwp/SettingsPage.xaml.cs
Labels: enhancement

#328 Retrieve actual mline index instead of mid
  libs/mrwebrtc/src/peer_connection.cpp
Labels: bug

#301 Only create local tracks if component is active
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime.asmdef
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime/PeerConnectionTests.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime/VideoSenderTests.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime/VideoSenderTests.cs.meta
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime/VideoSourceTests.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/AudioSender.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/MediaSender.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/VideoSender.cs
Labels: bug

#325 Use message struct for ICE candidates
  examples/TestAppUwp/Model/SessionModel.cs
  examples/TestAppUwp/NodeDssSignaler.cs
  examples/TestNetCoreConsole/NamedPipeSignaler.cs
  examples/TestNetCoreConsole/Program.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Examples/StandaloneDemo/LocalOnlySignaler.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Editor/EditorTests.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/Signaler.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
  libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
  libs/Microsoft.MixedReality.WebRTC/Tracing/MainEventSource.cs
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/src/interop/interop_api.cpp
  libs/mrwebrtc/src/peer_connection.cpp
  libs/mrwebrtc/src/peer_connection.h
  libs/mrwebrtc/test/data_channel_tests.cpp
  libs/mrwebrtc/test/peer_connection_test_helpers.h
  tests/Microsoft.MixedReality.WebRTC.Tests/PeerConnectionTestBase.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/PeerConnectionTests.cs
Labels: breaking change, clean-up

#330 Update win build scripts to handle variants
  tools/build/build.ps1
  tools/build/libwebrtc/build.ps1
  tools/build/libwebrtc/checkout.ps1
  tools/build/libwebrtc/mrwebrtc.ps1
Labels: breaking change, enhancement

#331 Update build docs after build.ps1 changes
  tools/build/libwebrtc/README.md
Labels: doc

#334 Add documentation for Android Studio debugging
  tools/build/android/debugging.md
  tools/build/android/docs/android-export-project.png
  tools/build/android/docs/android-studio-debugger-type.png
  tools/build/android/docs/lldb-symbols-folder.png
Labels: doc, platform:android

#337 More Android debugging docs
  tools/build/android/debugging.md
Labels: doc, platform:android

#338 Disable SceneVideoSender w/o async GPU readback
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/SceneVideoSender.cs
Labels: bug

#339 Split long log messages on Android for logcat
  libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs
Labels: enhancement, platform:android

#341 Add fulldebug config to Android project
  tools/build/android/webrtc-native/build.gradle
Labels: enhancement, platform:android

#342 Add/remove Source only if not null
  libs/mrwebrtc/src/toggle_audio_mixer.cpp
Labels: bug

#347 Add simple README to document libs/
  libs/README.md
Labels: doc

#350 Add release pipeline for Unity
  libs/unity/library/package.json
  libs/unity/samples/package.json
  tools/ci/computeNpmPackageVersion.ps1
  tools/ci/release-unity.yaml
  tools/ci/templates/jobs-cpp.yaml
  tools/ci/templates/jobs-cs-build.yaml
  tools/ci/templates/jobs-unity-package.yaml
Labels: enhancement

#365 Fix crash in TestAppUWP on invalid local peer ID
  examples/TestAppUwp/MainPage.xaml.cs
Labels: bug

#364 Fix C# library copy to Unity plugin after build
  libs/Microsoft.MixedReality.WebRTC/Microsoft.MixedReality.WebRTC.csproj
Labels: bug

#363 Add E_BUFFER_TOO_SMALL error code
  libs/Microsoft.MixedReality.WebRTC/Exceptions.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
  libs/mrwebrtc/include/result.h
Labels: enhancement

#362 Add verbose logging when destroying native objects
  libs/mrwebrtc/src/interop/external_video_track_source_interop.cpp
  libs/mrwebrtc/src/interop/local_audio_track_interop.cpp
  libs/mrwebrtc/src/interop/local_video_track_interop.cpp
  libs/mrwebrtc/src/interop/peer_connection_interop.cpp
  libs/mrwebrtc/src/ref_counted_base.h
Labels: enhancement

#366 Publish Unity packages to external NPM register
  tools/ci/release-unity.yaml
  tools/ci/templates/jobs-unity-package.yaml
  tools/ci/writeNpmrc.ps1
Labels: enhancement

#367 Add optional CG task to mrwebrtc build template
  tools/ci/ci-cpp.yaml
  tools/ci/computePdbPackageVars.ps1
  tools/ci/copyPdbsForBuilding.ps1
  tools/ci/copyPdbsForPackaging.ps1
  tools/ci/generateCppPackagesConfig.ps1
  tools/ci/mapVariables.ps1
  tools/ci/modifyCppProject.ps1
  tools/ci/templates/jobs-cpp.yaml
Labels: enhancement

#369 Update the .NET Core 3.0 tutorial
  docs/manual/cs/helloworld-cs-connection-core3.md
  docs/manual/cs/helloworld-cs-core3.md
  docs/manual/cs/helloworld-cs-mediatracks-core3.md
  docs/manual/cs/helloworld-cs-peerconnection-core3.md
  docs/manual/cs/helloworld-cs-setup-core3.md
  docs/manual/cs/helloworld-cs-signaling-core3.md
  examples/TestNetCoreConsole/Program.cs
Labels: doc

#361 Add mrsOptBool
  libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/src/utils.h
Labels: enhancement

#373 Add unified release pipeline for NuGet packages (Windows)
  libs/Microsoft.MixedReality.WebRTC/Microsoft.MixedReality.WebRTC.nuspec
  tools/ci/checkSigning.ps1
  tools/ci/ci-cpp.yaml
  tools/ci/modifyCppProject.ps1
  tools/ci/release-cpp.yaml
  tools/ci/release-unity.yaml
  tools/ci/templates/jobs-cpp.yaml
  tools/ci/templates/jobs-cslib-release-build.yaml
  tools/ci/templates/jobs-cslib-release-pack.yaml
  tools/ci/templates/jobs-cslib-release-test.yaml
  tools/ci/templates/jobs-mrwebrtc-release-build.yaml
  tools/ci/templates/jobs-mrwebrtc-release-pack.yaml
  tools/ci/templates/jobs-mrwebrtc-release-test.yaml
  tools/ci/templates/steps-mrwebrtc-test-win32.yaml
  tools/nuget/Desktop/Microsoft.MixedReality.WebRTC.Native.Desktop.nuspec
  tools/nuget/Desktop/Microsoft.MixedReality.WebRTC.Native.Desktop.props
  tools/nuget/Desktop/Microsoft.MixedReality.WebRTC.nuspec
  tools/nuget/UWP/Microsoft.MixedReality.WebRTC.Native.UWP.nuspec
  tools/nuget/UWP/Microsoft.MixedReality.WebRTC.Native.UWP.props
  tools/nuget/UWP/Microsoft.MixedReality.WebRTC.UWP.nuspec
Labels: enhancement, platform:uwp, platform:win32

#378 Fix Unity documentation generation
  docs/docfx.json
  docs/manual/cs/cs-peerconnection.md
  docs/manual/cs/cs-signaling.md
  docs/manual/cs/helloworld-cs-mediatracks-uwp.md
  docs/manual/helloworld-unity-connection.md
  docs/manual/unity-signaler.md
  libs/unity/library/Runtime/Scripts/PeerConnection.cs
Labels: bug, doc

#377 Add split audio track source
  examples/TestAppUwp/MediaPlayerPage.xaml.cs
  examples/TestAppUwp/ViewModel/AudioCaptureViewModel.cs
  examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
  examples/TestNetCoreConsole/Program.cs
  libs/Microsoft.MixedReality.WebRTC/AudioTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/AudioTrackSourceInterop.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/LocalAudioTrackInterop.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
  libs/Microsoft.MixedReality.WebRTC/LocalAudioTrack.cs
  libs/mrwebrtc/include/audio_track_source_interop.h
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/include/local_audio_track_interop.h
  libs/mrwebrtc/src/interop/audio_track_source_interop.cpp
  libs/mrwebrtc/src/interop/global_factory.cpp
  libs/mrwebrtc/src/interop/interop_api.cpp
  libs/mrwebrtc/src/interop/local_audio_track_interop.cpp
  libs/mrwebrtc/src/media/audio_track_source.cpp
  libs/mrwebrtc/src/media/audio_track_source.h
  libs/mrwebrtc/src/tracked_object.h
  libs/mrwebrtc/test/audio_track_source_tests.cpp
  libs/mrwebrtc/test/audio_track_tests.cpp
  tests/Microsoft.MixedReality.WebRTC.Tests/AudioTrackSourceTests.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/LocalAudioTrackTests.cs
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj.filters
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj.filters
  tools/build/mrwebrtc/win32/tests/mrwebrtc-win32-tests.vcxproj
Labels: breaking change, enhancement

#379 Add a glossary to the documentation
  docs/manual/glossary.md
  docs/manual/toc.md
  docs/template/mr-webrtc/styles/main.css
Labels: doc, enhancement
