Repository microsoft/MixedReality-WebRTC, pull requests merged in 2020-06, with the labels that each got.

#380 Add split video track source
  examples/TestAppUwp/MediaPlayerPage.xaml.cs
  examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
  examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
  examples/TestNetCoreConsole/Program.cs
  libs/Microsoft.MixedReality.WebRTC/ExternalVideoTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/LocalVideoTrackInterop.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/VideoTrackSourceInterop.cs
  libs/Microsoft.MixedReality.WebRTC/LocalVideoTrack.cs
  libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
  libs/Microsoft.MixedReality.WebRTC/VideoTrackSource.cs
  libs/mrwebrtc/include/external_video_track_source_interop.h
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/include/local_video_track_interop.h
  libs/mrwebrtc/include/video_track_source_interop.h
  libs/mrwebrtc/src/interop/global_factory.cpp
  libs/mrwebrtc/src/interop/interop_api.cpp
  libs/mrwebrtc/src/interop/local_video_track_interop.cpp
  libs/mrwebrtc/src/interop/video_track_source_interop.cpp
  libs/mrwebrtc/src/media/video_track_source.cpp
  libs/mrwebrtc/src/media/video_track_source.h
  libs/mrwebrtc/src/tracked_object.h
  libs/mrwebrtc/test/video_track_source_tests.cpp
  libs/mrwebrtc/test/video_track_tests.cpp
  tests/Microsoft.MixedReality.WebRTC.Tests/LocalVideoTrackTests.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/VideoTrackSourceTests.cs
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj.filters
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj.filters
  tools/build/mrwebrtc/win32/tests/mrwebrtc-win32-tests.vcxproj
Labels: breaking change, enhancement

#389 Fix vertical flip of video on OpenGL platforms
  libs/unity/library/Runtime/Scripts/Media/MediaPlayer.cs
  libs/unity/library/Runtime/Shaders/ARGBFeedShader.shader
  libs/unity/library/Runtime/Shaders/ARGBFeedShaderUnlit.shader
  libs/unity/library/Runtime/Shaders/YUVFeedShader.shader
  libs/unity/library/Runtime/Shaders/YUVFeedShaderUnlit.shader
Labels: bug

#391 Make Track.CreateFromSource synchronous
  examples/TestAppUwp/ViewModel/AudioCaptureViewModel.cs
  examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
  examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
  examples/TestNetCoreConsole/Program.cs
  libs/Microsoft.MixedReality.WebRTC/LocalAudioTrack.cs
  libs/Microsoft.MixedReality.WebRTC/LocalVideoTrack.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/LocalAudioTrackTests.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/LocalVideoTrackTests.cs
Labels: breaking change, enhancement

#386 Fix data channel issues
  libs/mrwebrtc/include/data_channel_interop.h
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/src/data_channel.cpp
  libs/mrwebrtc/src/data_channel.h
  libs/mrwebrtc/src/interop/data_channel_interop.cpp
  libs/mrwebrtc/src/interop/global_factory.cpp
  libs/mrwebrtc/src/interop/global_factory.h
  libs/mrwebrtc/src/peer_connection.cpp
  libs/mrwebrtc/test/data_channel_tests.cpp
Labels: bug

#392 Remove abstraction of ExternalVideoTrackSource
  libs/mrwebrtc/src/interop/interop_api.cpp
  libs/mrwebrtc/src/interop/local_video_track_interop.cpp
  libs/mrwebrtc/src/media/external_video_track_source.cpp
  libs/mrwebrtc/src/media/external_video_track_source.h
  libs/mrwebrtc/src/media/external_video_track_source_impl.h
  libs/mrwebrtc/src/pch.h
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj.filters
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj.filters
Labels: clean-up

#398 Make C# external video track source a proper source
  examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
  examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
  examples/TestNetCoreConsole/Program.cs
  libs/Microsoft.MixedReality.WebRTC/DeviceVideoTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/ExternalVideoTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/DeviceVideoTrackSourceInterop.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/LocalVideoTrackInterop.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/VideoTrackSourceInterop.cs
  libs/Microsoft.MixedReality.WebRTC/LocalAudioTrack.cs
  libs/Microsoft.MixedReality.WebRTC/LocalVideoTrack.cs
  libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
  libs/Microsoft.MixedReality.WebRTC/VideoTrackSource.cs
  libs/mrwebrtc/include/device_video_track_source_interop.h
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/include/local_video_track_interop.h
  libs/mrwebrtc/include/video_track_source_interop.h
  libs/mrwebrtc/src/interop/device_video_track_source_interop.cpp
  libs/mrwebrtc/src/interop/local_video_track_interop.cpp
  libs/mrwebrtc/src/interop/video_track_source_interop.cpp
  libs/mrwebrtc/src/media/device_video_track_source.cpp
  libs/mrwebrtc/src/media/device_video_track_source.h
  libs/mrwebrtc/src/media/external_video_track_source.cpp
  libs/mrwebrtc/src/media/external_video_track_source.h
  libs/mrwebrtc/src/media/video_track_source.cpp
  libs/mrwebrtc/src/media/video_track_source.h
  libs/mrwebrtc/src/tracked_object.h
  libs/mrwebrtc/src/utils.cpp
  libs/mrwebrtc/test/device_video_track_source_tests.cpp
  libs/mrwebrtc/test/external_video_track_source_tests.cpp
  libs/mrwebrtc/test/transceiver_tests.cpp
  libs/mrwebrtc/test/video_track_tests.cpp
  tests/Microsoft.MixedReality.WebRTC.Tests/LocalVideoTrackTests.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/VideoTrackSourceTests.cs
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj.filters
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj.filters
  tools/build/mrwebrtc/win32/tests/mrwebrtc-win32-tests.vcxproj
Labels: breaking change, enhancement

#400 Add Windows DLL signing to Unity UPM release pipeline
  tools/ci/release-cpp.yaml
  tools/ci/release-unity.yaml
  tools/ci/templates/jobs-unity-package.yaml
Labels: enhancement

#407 Add Android build to Unity release pipeline
  tools/build/libwebrtc/build.sh
  tools/build/libwebrtc/checkout.sh
  tools/build/libwebrtc/config.sh
  tools/build/libwebrtc/lib.sh
  tools/ci/release-unity.yaml
  tools/ci/templates/jobs-libwebrtc-android.yaml
  tools/ci/templates/jobs-unity-package.yaml
  tools/ci/templates/steps-linux-clean-image.yaml
Labels: platform:android

#411 Update docs front page with branch/version
  docs/index.md
Labels: doc

#417 Fix invalid use of size_t instead of uint64_t
  libs/mrwebrtc/test/object_tests.cpp
Labels: bug

#416 Remove legacy string wrapper
  libs/mrwebrtc/src/data_channel.cpp
  libs/mrwebrtc/src/data_channel.h
  libs/mrwebrtc/src/media/media_track.h
  libs/mrwebrtc/src/peer_connection.cpp
  libs/mrwebrtc/src/peer_connection.h
  libs/mrwebrtc/src/str.cpp
  libs/mrwebrtc/src/str.h
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj.filters
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj.filters
Labels: clean-up

#421 [TestAppUWP] Assign selected video profile
  examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
Labels: bug

#420 Split audio device source and base audio source
  examples/TestAppUwp/ViewModel/AudioCaptureViewModel.cs
  examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
  examples/TestNetCoreConsole/Program.cs
  libs/Microsoft.MixedReality.WebRTC/AudioTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/DeviceAudioTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/DeviceVideoTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/AudioTrackSourceInterop.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/DeviceAudioTrackSourceInterop.cs
  libs/mrwebrtc/include/audio_track_source_interop.h
  libs/mrwebrtc/include/device_audio_track_source_interop.h
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/src/interop/audio_track_source_interop.cpp
  libs/mrwebrtc/src/interop/device_audio_track_source_interop.cpp
  libs/mrwebrtc/src/media/audio_track_source.cpp
  libs/mrwebrtc/src/media/audio_track_source.h
  libs/mrwebrtc/src/media/device_audio_track_source.cpp
  libs/mrwebrtc/src/media/device_audio_track_source.h
  libs/mrwebrtc/src/tracked_object.h
  libs/mrwebrtc/src/utils.cpp
  libs/mrwebrtc/test/audio_track_tests.cpp
  libs/mrwebrtc/test/device_audio_track_source_tests.cpp
  tests/Microsoft.MixedReality.WebRTC.Tests/AudioTrackSourceTests.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/LocalAudioTrackTests.cs
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj
  tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj.filters
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj
  tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj.filters
  tools/build/mrwebrtc/win32/tests/mrwebrtc-win32-tests.vcxproj
Labels: breaking change, clean-up

#423 Fix CMakeLists.txt after recent changes
  tools/build/android/webrtc-native/src/main/cpp/CMakeLists.txt
Labels: bug

#427 Add snippet to setup local transceivers and tracks
  examples/TestAppUwp/AddVideoTrackPage.xaml
  examples/TestAppUwp/MainPage.xaml.cs
  examples/TestAppUwp/Model/SessionModel.cs
  examples/TestAppUwp/ViewModel/AudioCaptureViewModel.cs
  examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
Labels: enhancement

#429 Update the C# UWP tutorial to reflect the new API
  docs/manual/cs/helloworld-cs-connection-uwp.md
  docs/manual/cs/helloworld-cs-mediatracks-core3.md
  docs/manual/cs/helloworld-cs-mediatracks-uwp.md
  docs/manual/cs/helloworld-cs-setup-uwp.md
  docs/manual/cs/helloworld-cs-signaling-uwp.md
  docs/manual/cs/helloworld-cs-uwp.md
  docs/manual/migration-guide.md
Labels: doc

#428 Miscellaneous docs appearance fixes
  docs/docfx.json
  docs/template/mr-webrtc/layout/_master.tmpl
  docs/template/mr-webrtc/partials/logo.tmpl.partial
  docs/template/mr-webrtc/styles/main.css
Labels: doc
