Repository microsoft/MixedReality-WebRTC, pull requests merged in 2020-07, with the labels that each got.

#435 Recycle ARGB buffer when frame rotates
  libs/mrwebrtc/src/video_frame_observer.cpp
  libs/mrwebrtc/src/video_frame_observer.h
Labels: bug

#433 Android video capture
  .gitignore
  examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
  examples/TestNetCoreConsole/Program.cs
  libs/Microsoft.MixedReality.WebRTC/DeviceAudioTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/DeviceVideoTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/DeviceVideoTrackSourceInterop.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
  libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
  libs/Microsoft.MixedReality.WebRTC/Tracing/MainEventSource.cs
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/src/interop/interop_api.cpp
  libs/mrwebrtc/src/media/device_video_track_source.cpp
  libs/mrwebrtc/src/media/device_video_track_source.h
  libs/mrwebrtc/src/media/video_track_source.h
  libs/mrwebrtc/src/mrs_errors.cpp
  libs/mrwebrtc/src/mrs_errors.h
  libs/mrwebrtc/src/pch.h
  libs/mrwebrtc/src/utils.h
  libs/unity/library/Runtime/Scripts/Media/MicrophoneSource.cs
  libs/unity/library/Runtime/Scripts/Media/WebcamSource.cs
  libs/unity/library/Runtime/Scripts/PeerConnection.cs
  tests/Microsoft.MixedReality.WebRTC.Tests/VideoEnum.cs
  tools/build/android/settings.gradle
  tools/build/android/webrtc-native/build.gradle
  tools/build/android/webrtc-native/src/main/cpp/CMakeLists.txt
  tools/build/android/webrtc-native/src/main/cpp/jni_onload.cpp
  tools/build/android/webrtc-native/src/main/java/com/microsoft/mixedreality/webrtc/AndroidCameraInterop.java
  tools/build/android/webrtc-native/src/main/java/com/microsoft/mixedreality/webrtc/VideoCaptureDeviceInfo.java
  tools/build/android/webrtc-native/src/main/java/com/microsoft/mixedreality/webrtc/VideoCaptureFormatInfo.java
  tools/build/libwebrtc/build.sh
Labels: breaking change, enhancement

#432 Refactor receivers hierarchy
  examples/TestAppUwp/MediaPlayerPage.xaml.cs
  libs/Microsoft.MixedReality.WebRTC/AudioTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/DeviceVideoTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/ExternalVideoTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/IAudioSource.cs
  libs/Microsoft.MixedReality.WebRTC/IAudioTrack.cs
  libs/Microsoft.MixedReality.WebRTC/IVideoSource.cs
  libs/Microsoft.MixedReality.WebRTC/IVideoTrack.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/ExternalVideoTrackSourceInterop.cs
  libs/Microsoft.MixedReality.WebRTC/LocalAudioTrack.cs
  libs/Microsoft.MixedReality.WebRTC/LocalVideoTrack.cs
  libs/Microsoft.MixedReality.WebRTC/RemoteAudioTrack.cs
  libs/Microsoft.MixedReality.WebRTC/RemoteVideoTrack.cs
  libs/Microsoft.MixedReality.WebRTC/VideoFrame.cs
  libs/Microsoft.MixedReality.WebRTC/VideoTrackSource.cs
  libs/unity/library/Editor/MicrophoneSourceEditor.cs
  libs/unity/library/Editor/VideoRendererEditor.cs
  libs/unity/library/Runtime/Scripts/Media/AudioReceiver.cs
  libs/unity/library/Runtime/Scripts/Media/AudioRenderer.cs
  libs/unity/library/Runtime/Scripts/Media/AudioRenderer.cs.meta
  libs/unity/library/Runtime/Scripts/Media/AudioTrackSource.cs
  libs/unity/library/Runtime/Scripts/Media/CustomVideoSource.cs
  libs/unity/library/Runtime/Scripts/Media/IAudioSource.cs
  libs/unity/library/Runtime/Scripts/Media/IAudioSource.cs.meta
  libs/unity/library/Runtime/Scripts/Media/IVideoSource.cs
  libs/unity/library/Runtime/Scripts/Media/MediaLine.cs
  libs/unity/library/Runtime/Scripts/Media/MediaReceiver.cs
  libs/unity/library/Runtime/Scripts/Media/MediaReceiver.cs.meta
  libs/unity/library/Runtime/Scripts/Media/MicrophoneSource.cs
  libs/unity/library/Runtime/Scripts/Media/VideoReceiver.cs
  libs/unity/library/Runtime/Scripts/Media/VideoRenderer.cs
  libs/unity/library/Runtime/Scripts/Media/VideoRendererSource.cs
  libs/unity/library/Runtime/Scripts/Media/VideoRendererSource.cs.meta
  libs/unity/library/Runtime/Scripts/Media/VideoTrackSource.cs
  libs/unity/library/Runtime/Scripts/Media/WebcamSource.cs
  libs/unity/library/Runtime/Scripts/Media/WorkQueue.cs
  libs/unity/library/Runtime/Scripts/PeerConnection.cs
  libs/unity/library/Tests/Runtime/MediaLineTests.cs
  libs/unity/library/Tests/Runtime/VideoSenderTests.cs
  libs/unity/library/Tests/Runtime/VideoSourceTests.cs
  libs/unity/samples/Runtime/Scenes/VideoChatDemo/VideoChatDemo.unity
  libs/unity/samples/Runtime/Scripts/UniformColorVideoSource.cs
Labels: breaking change, enhancement

#448 Reintroduce MediaTrackSource
  libs/unity/library/Runtime/Scripts/Media/AudioTrackSource.cs
  libs/unity/library/Runtime/Scripts/Media/IMediaTrackSource.cs
  libs/unity/library/Runtime/Scripts/Media/MediaLine.cs
  libs/unity/library/Runtime/Scripts/Media/MediaReceiver.cs
  libs/unity/library/Runtime/Scripts/Media/MediaTrackSource.cs
  libs/unity/library/Runtime/Scripts/Media/MediaTrackSource.cs.meta
  libs/unity/library/Runtime/Scripts/Media/VideoTrackSource.cs
  libs/unity/library/Tests/Runtime/MediaLineTests.cs
Labels: breaking change, clean-up

#453 Add Python build script for Windows builds
  README.undock.md
  tools/build/build.py
Labels: enhancement

#457 Add support for multi-config build to build.py
  tools/build/build.py
Labels: enhancement

#430 Init/close PeerConnection on enable/disable
  docs/manual/unity/unity-peerconnection.md
  docs/manual/unity/unity-peerconnection.png
  libs/Microsoft.MixedReality.WebRTC/Transceiver.cs
  libs/unity/library/Editor/PeerConnectionEditor.cs
  libs/unity/library/Runtime/Scripts/Media/MediaLine.cs
  libs/unity/library/Runtime/Scripts/PeerConnection.cs
  libs/unity/library/Tests/Runtime/LocalOnlySignaler.cs
  libs/unity/library/Tests/Runtime/MediaLineTests.cs
  libs/unity/library/Tests/Runtime/PeerConnectionTests.cs
  libs/unity/library/Tests/Runtime/VideoSenderTests.cs
  libs/unity/library/Tests/Runtime/VideoSourceTests.cs
Labels: bug

#477 Documentation fixes and updates ahead of 2.0.0
  docs/manual/cs/helloworld-cs-mediatracks-uwp.md
  docs/manual/cs/helloworld-cs-setup-core3.md
  docs/manual/cs/helloworld-cs-setup-uwp.md
  docs/manual/download.md
  docs/manual/installation.md
  docs/manual/migration-guide.md
  docs/manual/unity/helloworld-unity-localvideo.md
  docs/manual/unity/unity-localvideosource.md
  docs/manual/unity/unity-mediaplayer.md
  docs/manual/unity/unity-mediaplayer.png
  docs/manual/unity/unity-peerconnection.md
Labels: doc

#481 Fix Unity release Android artifact staging path
  tools/ci/templates/jobs-libwebrtc-android.yaml
Labels: bug

#484 Minor docs fixes
  docs/manual/cs/helloworld-cs-mediatracks-core3.md
  docs/manual/cs/helloworld-cs-setup-core3.md
Labels: doc

#485 Add parity to build.py and delete build.ps1
  tools/build/build.ps1
  tools/build/build.py
Labels: undock

#487 Enumerate video profiles and filter capture formats
  examples/TestAppUwp/AddVideoTrackPage.xaml
  examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
  libs/Microsoft.MixedReality.WebRTC/DeviceVideoTrackSource.cs
  libs/Microsoft.MixedReality.WebRTC/Interop/DeviceVideoTrackSourceInterop.cs
  libs/mrwebrtc/include/interop_api.h
  libs/mrwebrtc/src/interop/interop_api.cpp
  libs/mrwebrtc/src/media/device_video_track_source.cpp
  libs/mrwebrtc/src/media/device_video_track_source.h
Labels: enhancement

#490 [Unity] Fix wrong return type in format enum
  libs/unity/library/Runtime/Scripts/PeerConnection.cs
Labels: bug

#494 Work around broken getSupportedFormats() in UWP
  libs/mrwebrtc/src/media/device_video_track_source.cpp
Labels: bug
